volumes:
  ckan_storage:
    driver_opts:
      type: none
      o: bind
      device: /data/ckan
  pg_data:
  solr_data:
  pip_cache:
  site_packages:

services:
  ckan:
    logging:
      options:
        max-size: 100m
    build:
      dockerfile: ckan/Dockerfile
      args:
        - TZ=${TZ}
    networks:
      - ckannet
      - dbnet
      - solrnet
      - redisnet
    env_file:
      - .env.config
      - .env.secrets
    depends_on:
      db:
        condition: service_healthy
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - /data/ckan:/var/lib/ckan
      - pip_cache:/root/.cache/pip
      - site_packages:/usr/lib/python3.10/site-packages
    restart: unless-stopped
    ports:
      - '${CKAN_PORT_HOST}:5000'
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '-qO',
          '/dev/null',
          'http://localhost:5000/api/action/status_show',
        ]
      interval: 60s
      timeout: 10s
      retries: 3

  datapusher:
    logging:
      options:
        max-size: 100m
    networks:
      - ckannet
      - dbnet
    image: ckan/ckan-base-datapusher:0.0.20
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '-qO', '/dev/null', 'http://localhost:8800']
      interval: 60s
      timeout: 10s
      retries: 3
    env_file:
      - .env.config
      - .env.secrets

  db:
    logging:
      options:
        max-size: 100m
    build:
      context: postgresql/
    networks:
      - dbnet
    env_file:
      - .env.config
      - .env.secrets
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}', '-d', '${POSTGRES_DB}']

  solr:
    logging:
      options:
        max-size: 100m
    networks:
      - solrnet
    image: ckan/ckan-solr:2.9-solr9-spatial
    ports:
      - 8983:8983
    volumes:
      - solr_data:/var/solr
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '-qO', '/dev/null', 'http://localhost:8983/solr/']

  redis:
    logging:
      options:
        max-size: 100m
    image: redis:6
    networks:
      - redisnet
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', '-e', 'QUIT']

networks:
  webnet:
  ckannet:
  solrnet:
    internal: true
  dbnet:
    internal: true
  redisnet:
    internal: true
